### ISSUE TITLE
address not found

### ISSUE THREAD

**Issue by avm70** [DJViau/bid-on-auctions#1]
Hello, I changed seaport.createBuyOrder to seaport.createSellOrder. Made all like in readme and now have a error ADDRESS_NOT_FOUND. I'm new to js and will glad to any help.

console log:
`{ code: -32000, message: 'execution reverted' }`
`Error: execution reverted`
`at Object.InvalidResponse (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/opensea-js/node_modules/web3/lib/web3/errors.js:38:16)`
`at /home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/opensea-js/node_modules/web3/lib/web3/requestmanager.js:86:36`
`at XMLHttpRequest.request.onreadystatechange (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/opensea-js/node_modules/web3/lib/web3/httpprovider.js:129:7)`
`    at XMLHttpRequestEventTarget.dispatchEvent (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)`
`    at XMLHttpRequest._setReadyState (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/xhr2-cookies/xml-http-request.ts:219:8)`
`    at XMLHttpRequest._onHttpResponseEnd (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/xhr2-cookies/xml-http-request.ts:345:8)`
`    at IncomingMessage.<anonymous> (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/xhr2-cookies/xml-http-request.ts:311:39)`
`    at emitNone (events.js:111:20)`
`    at IncomingMessage.emit (events.js:208:7)`
`    at endReadableNT (_stream_readable.js:1064:12)`
`    at _combinedTickCallback (internal/process/next_tick.js:138:11)`
`    at process._tickCallback (internal/process/next_tick.js:180:9)`
`Already approved proxy for all tokens`
`Error: ADDRESS_NOT_FOUND: 0x2c3584694aae0422c9ae196bf2c42c09********`
`    at MnemonicWalletSubprovider._findDerivedKeyInfoForAddress (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/src/subproviders/mnemonic_wallet.ts:144:19)`
`    at MnemonicWalletSubprovider._privateKeyWalletForAddress (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/src/subproviders/mnemonic_wallet.ts:132:37)`
`    at MnemonicWalletSubprovider.<anonymous> (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/src/subproviders/mnemonic_wallet.ts:108:39)`
`    at step (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/mnemonic_wallet.js:45:23)`
`    at Object.next (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/mnemonic_wallet.js:26:53)`
`    at /home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/mnemonic_wallet.js:20:71`
`    at new Promise (<anonymous>)`
`    at __awaiter (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/mnemonic_wallet.js:16:12)`
`    at MnemonicWalletSubprovider.signPersonalMessageAsync (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/mnemonic_wallet.js:155:16)`
`    at MnemonicWalletSubprovider.<anonymous> (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/src/subproviders/base_wallet_subprovider.ts:94:55)`
`    at step (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/base_wallet_subprovider.js:56:23)`
`    at Object.next (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/base_wallet_subprovider.js:37:53)`
`    at /home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/base_wallet_subprovider.js:31:71`
`    at new Promise (<anonymous>)`
`    at __awaiter (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/base_wallet_subprovider.js:27:12)`
`    at MnemonicWalletSubprovider.BaseWalletSubprovider.handleRequest (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/@0x/subproviders/lib/src/subproviders/base_wallet_subprovider.js:109:16)`
`Failed: Error: You declined to authorize your auction`
`    at OpenSeaPort.<anonymous> (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/opensea-js/src/seaport.ts:655:13)`
`    at step (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/opensea-js/lib/seaport.js:40:23)`
`    at Object.throw (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/opensea-js/lib/seaport.js:21:53)`
`    at rejected (/home/alexandr/opensea_scripts/bid-on-auctions-master/node_modules/opensea-js/lib/seaport.js:13:65)`
`    at <anonymous>`
`    at runMicrotasksCallback (internal/process/next_tick.js:121:5)`
`    at _combinedTickCallback (internal/process/next_tick.js:131:7)`
`    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by avm70** [comment]
That was a problem with infura_key. Now all works fine.
